import styled from "@emotion/styled";
import type { NextPage } from "next";
import Head from "next/head";
import Header from "../Header";
import LibraryMaintainer from "../LibraryMaintainer";
import Loading from "../Loading";
import NoOne from "../NoOne";
import useVersions from "../useVersions";
import WebsiteServiceMaker from "../WebsiteServiceMaker";

const Home: NextPage = () => {
  const versions = useVersions();

  return (
    <div style={{ textAlign: "center" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {versions === null && <Loading />}

      {versions && (
        <div>
          <h2>If you&apos;re a...</h2>

          <Grid>
            <div>
              <LibraryMaintainer />
            </div>
            <div>
              <WebsiteServiceMaker />
            </div>
          </Grid>

          <NoOneWrapper>
            <NoOne />
          </NoOneWrapper>
        </div>
      )}
    </div>
  );
};
export default Home;

const Grid = styled.div`
  display: grid;
  grid-auto-columns: 1fr;
  grid-auto-flow: column;

  @media only screen and (max-width: 700px) {
    grid-auto-flow: row;
  }
`;

const NoOneWrapper = styled.div`
  margin-top: 4em;
  margin-bottom: 2em;
`;
