name: CD
on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    needs:
      - ci

    steps:
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: Build
          path: ./out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
